'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';
type Theme = 'light' | 'dark' | 'night';

interface SettingsContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    theme: Theme;
    setTheme: (theme: Theme) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        dashboard: 'Dashboard',
        dashboardOverview: 'Dashboard Overview',
        dashboardWelcome: 'Welcome back, monitor your fleet status below.',
        live: 'Live',
        total: 'Total',
        actionReq: 'Action Req',
        dataVerified: 'Data verified',
        complianceText: 'Your fleet is maintaining exceptional temperature stability. Only {count} critical incidents reported in the last 24 hours.',
        viewPatternAnalysis: 'View Pattern Analysis',
        recentActivity: 'Recent Activity',
        temperatureWarning: 'Temperature Warning',
        viewAllHistory: 'View All History',
        nationalDashboard: 'National Dashboard',
        monitoringSystem: 'Real-time cold chain monitoring system',
        devices: 'Devices',
        manageDevices: 'Manage and monitor your IoT hardware infrastructure',
        searchDevices: 'Search by ID or facility...',
        addDevice: 'Register Device',
        noDevicesFound: 'No devices match your search criteria.',
        map: 'Map View',
        alerts: 'Alerts',
        manageAlerts: 'Review and take action on system alerts',
        allAlerts: 'Alert Repository',
        clearAll: 'Mark all as read',
        severity: 'Severity',
        reports: 'Reports',
        generateReports: 'Generate and export regulatory compliance data',
        exportPDF: 'Export PDF',
        facilities: 'Facilities',
        manageLocations: 'National database of medical and storage infrastructure',
        users: 'User Management',
        manageUsers: 'Control access and manage team members',
        settings: 'Settings',
        preferences: 'Manage your account preferences and application behavior',
        profile: 'Profile Settings',
        appearance: 'Appearance',
        logout: 'Logout',
        verifying: 'Verifying session...',
        lastUpdated: 'Last updated',
        refresh: 'Refresh',
        filter: 'Filter',
        totalDevices: 'Total Devices',
        registeredUnits: 'Registered units',
        healthy: 'Healthy',
        warnings: 'Warnings',
        requireReview: 'Require review',
        critical: 'Critical',
        actionRequired: 'Action required',
        complianceRate: 'Compliance Rate',
        complianceDesc: 'Percentage of devices maintaining proper temperature ranges across the selected region',
        monitoringActive: 'Monitoring active',
        readings24h: 'Readings (24h)',
        wilayas: 'Wilayas Covered',
        activeUnits: 'Active Units',
        reliability: 'System Reliability',
        assetLocation: 'Asset Geolocation',
        activeMarkers: 'Active GPS markers',
        recentAlerts: 'Recent Alerts',
        alertsDesc: 'Notifications requiring attention',
        tempTrend: 'Temperature Aggregation (24h)',
        trendDesc: 'System-wide temperature and humidity trends',
        monitoredAssets: 'Monitored Assets',
        devicesDesc: 'Recently updated devices',
        viewAll: 'View All',
        noDevices: 'No devices tracked yet.',
        language: 'Language',
        theme: 'Theme',
        unauthorized: 'Unauthorized',
        backToLogin: 'Back to Login',
        allClear: 'All Clear!',
        noAlerts: 'No active alerts at the moment',
        welcomeBack: 'Welcome Back',
        signInDesc: 'Sign in to access your dashboard',
        email: 'Email Address',
        password: 'Password',
        signIn: 'Sign In',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot password?',
        securityNotice: 'Protected by 256-bit SSL encryption',
        // Alerts
        systemNotifications: 'System Notifications',
        systemNotificationsDesc: 'Real-time alerts requiring attention',
        activeAlerts: 'Active Alerts',
        markAllRead: 'Mark All Read',
        applyFilters: 'Apply Filters',
        // Facilities
        facilitiesNetwork: 'Facilities Network',
        facilitiesDesc: 'Manage all hospital and warehouse nodes',
        searchFacilities: 'Search facilities...',
        newFacility: 'New Facility',
        hospital: 'Hospital',
        warehouse: 'Warehouse',
        clinic: 'Clinic',
        hub: 'Hub',
        storage: 'Storage',
        remote: 'Remote',
        // Devices
        registerNewNode: 'Register New Node',
        identity: 'Identity',
        serialNumber: 'Serial Number',
        type: 'Type',
        location: 'Location',
        select: 'Select...',
        parameters: 'Parameters',
        target: 'TARGET',
        min: 'MIN',
        max: 'MAX',
        cancel: 'Cancel',
        status: 'Status',
        lastReading: 'Last Reading',
        battery: 'Battery',
        actions: 'Actions',
        edit: 'Edit',
        delete: 'Delete',
        viewDetails: 'View Details',
        deviceRegistered: 'Device registered successfully',
        registrationFailed: 'Registration failed',
        // Common
        active: 'Active',
        loading: 'Loading...',
        save: 'Save',
        close: 'Close',
        error: 'Error',
        success: 'Success',
        logs: 'Logs',
        temp: 'Temp',
        current: 'Current',
        fridge: 'Fridge',
        freezer: 'Freezer',
        device: 'Device',
        info: 'Info',
        unit: 'Unit',
        sensors: 'Sensors',
        sensorState: 'Sensor State',
        online: 'Online',
        offline: 'Offline',
        sendingData: 'Sending Data',
    },
    fr: {
        dashboard: 'Tableau de bord',
        dashboardOverview: 'Vue d\'ensemble',
        dashboardWelcome: 'Bon retour, surveillez l\'état de votre flotte ci-dessous.',
        live: 'En direct',
        total: 'Total',
        actionReq: 'Action requise',
        dataVerified: 'Données vérifiées',
        complianceText: 'Votre flotte maintient une stabilité de température exceptionnelle. Seuls {count} incidents critiques signalés au cours des dernières 24 heures.',
        viewPatternAnalysis: 'Voir l\'analyse des tendances',
        recentActivity: 'Activité récente',
        temperatureWarning: 'Avertissement de température',
        viewAllHistory: 'Voir tout l\'historique',
        nationalDashboard: 'Tableau de bord national',
        monitoringSystem: 'Système de surveillance de la chaîne du froid en temps réel',
        devices: 'Appareils',
        manageDevices: 'Gérez et surveillez votre infrastructure matérielle IoT',
        searchDevices: 'Rechercher par ID ou établissement...',
        addDevice: 'Enregistrer un appareil',
        noDevicesFound: 'Aucun appareil ne correspond à vos critères.',
        map: 'Carte',
        alerts: 'Alertes',
        manageAlerts: 'Examinez et agissez sur les alertes système',
        allAlerts: 'Répertoire des alertes',
        clearAll: 'Tout marquer comme lu',
        severity: 'Gravité',
        reports: 'Rapports',
        generateReports: 'Générez et exportez les données de conformité réglementaire',
        exportPDF: 'Exporter PDF',
        facilities: 'Établissements',
        manageLocations: 'Base de données nationale des infrastructures médicales',
        users: 'Gestion utilisateurs',
        manageUsers: 'Contrôlez les accès et gérez les membres de l\'équipe',
        settings: 'Paramètres',
        preferences: 'Gérez vos préférences de compte',
        profile: 'Profil',
        appearance: 'Apparence',
        logout: 'Déconnexion',
        verifying: 'Vérification de la session...',
        lastUpdated: 'Dernière mise à jour',
        refresh: 'Actualiser',
        filter: 'Filtrer',
        totalDevices: 'Total Appareils',
        registeredUnits: 'Unités enregistrées',
        healthy: 'Sain',
        warnings: 'Avertissements',
        requireReview: 'Nécessite examen',
        critical: 'Critique',
        actionRequired: 'Action requise',
        complianceRate: 'Taux de conformité',
        complianceDesc: 'Pourcentage d\'appareils maintenant les plages de température dans la région sélectionnée',
        monitoringActive: 'Surveillance active',
        readings24h: 'Lectures (24h)',
        wilayas: 'Wilayas couvertes',
        activeUnits: 'Unités actives',
        reliability: 'Fiabilité système',
        assetLocation: 'Géolocalisation des actifs',
        activeMarkers: 'Marqueurs GPS actifs',
        recentAlerts: 'Alertes récentes',
        alertsDesc: 'Notifications nécessitant une attention',
        tempTrend: 'Agrégation temp. (24h)',
        trendDesc: 'Tendances de température et d\'humidité à l\'échelle du système',
        monitoredAssets: 'Actifs surveillés',
        devicesDesc: 'Appareils récemment mis à jour',
        viewAll: 'Voir tout',
        noDevices: 'Aucun appareil suivi pour le moment.',
        language: 'Langue',
        theme: 'Thème',
        unauthorized: 'Non autorisé',
        backToLogin: 'Retour à la connexion',
        allClear: 'Tout est en ordre !',
        noAlerts: 'Aucune alerte active pour le moment',
        welcomeBack: 'Bon retour',
        signInDesc: 'Connectez-vous pour accéder à votre tableau de bord',
        email: 'Adresse Email',
        password: 'Mot de passe',
        signIn: 'Se connecter',
        rememberMe: 'Se souvenir de moi',
        forgotPassword: 'Mot de passe oublié ?',
        securityNotice: 'Protégé par cryptage SSL 256 bits',
        // Alerts
        systemNotifications: 'Notifications Système',
        systemNotificationsDesc: 'Alertes en temps réel nécessitant une attention',
        activeAlerts: 'Alertes Actives',
        markAllRead: 'Tout marquer comme lu',
        applyFilters: 'Appliquer les filtres',
        // Facilities
        facilitiesNetwork: 'Réseau d\'Établissements',
        facilitiesDesc: 'Gérer tous les nœuds hospitaliers et d\'entrepôts',
        searchFacilities: 'Rechercher des établissements...',
        newFacility: 'Nouvel Établissement',
        hospital: 'Hôpital',
        warehouse: 'Entrepôt',
        clinic: 'Clinique',
        hub: 'Pôle',
        storage: 'Stockage',
        remote: 'Distant',
        // Devices
        registerNewNode: 'Enregistrer un nouveau nœud',
        identity: 'Identité',
        serialNumber: 'Numéro de série',
        type: 'Type',
        location: 'Emplacement',
        select: 'Sélectionner...',
        parameters: 'Paramètres',
        target: 'CIBLE',
        min: 'MIN',
        max: 'MAX',
        cancel: 'Annuler',
        status: 'Statut',
        lastReading: 'Dernière lecture',
        battery: 'Batterie',
        actions: 'Actions',
        edit: 'Modifier',
        delete: 'Supprimer',
        viewDetails: 'Voir détails',
        deviceRegistered: 'Appareil enregistré avec succès',
        registrationFailed: 'Échec de l\'enregistrement',
        // Common
        active: 'Actif',
        loading: 'Chargement...',
        save: 'Enregistrer',
        close: 'Fermer',
        error: 'Erreur',
        success: 'Succès',
        logs: 'Journaux',
        temp: 'Temp.',
        current: 'Actuel',
        fridge: 'Réfrigérateur',
        freezer: 'Congélateur',
        device: 'Appareil',
        info: 'Info',
        unit: 'Unité',
        sensors: 'Capteurs',
        sensorState: 'État des capteurs',
        online: 'En ligne',
        offline: 'Hors ligne',
        sendingData: 'Envoi de données',
    },
    ar: {
        dashboard: 'لوحة التحكم',
        dashboardOverview: 'نظرة عامة',
        dashboardWelcome: 'مرحبًا بعودتك، راقب حالة أسطولك أدناه.',
        live: 'مباشر',
        total: 'الإجمالي',
        actionReq: 'إجراء مطلوب',
        dataVerified: 'تم التحقق من البيانات',
        complianceText: 'يحافظ أسطولك على استقرار استثنائي. تم الإبلاغ عن {count} حوادث حرجة فقط في آخر 24 ساعة.',
        viewPatternAnalysis: 'عرض تحليل الأنماط',
        recentActivity: 'النشاط الأخير',
        temperatureWarning: 'تحذير درجة الحرارة',
        viewAllHistory: 'عرض كل السجل',
        nationalDashboard: 'لوحة التحكم الوطنية',
        monitoringSystem: 'نظام مراقبة سلسلة التبريد في الوقت الفعلي',
        devices: 'الأجهزة',
        manageDevices: 'إدارة ومراقبة البنية التحتية لأجهزة إنترنت الأشياء',
        searchDevices: 'البحث حسب المعرف أو المرفق...',
        addDevice: 'تسجيل جهاز',
        noDevicesFound: 'لا توجد أجهزة تطابق معايير البحث الخاصة بك.',
        map: 'عرض الخريطة',
        alerts: 'التنبيهات',
        manageAlerts: 'مراجعة واتخاذ إجراء بشأن تنبيهات النظام',
        allAlerts: 'مستودع التنبيهات',
        clearAll: 'تحديد الكل كمقروء',
        severity: 'الخطورة',
        reports: 'التقارير',
        generateReports: 'إنشاء وتصدير بيانات الامتثال التنظيمي',
        exportPDF: 'تصدير PDF',
        facilities: 'المرافق',
        manageLocations: 'قاعدة البيانات الوطنية للبنية التحتية الطبية والتخزينية',
        users: 'إدارة المستخدمين',
        manageUsers: 'التحكم في الوصول وإدارة أعضاء الفريق',
        settings: 'الإعدادات',
        preferences: 'إدارة تفضيلات حسابك وسلوك التطبيق',
        profile: 'إعدادات الملف الشخصي',
        appearance: 'المظهر',
        logout: 'تسجيل الخروج',
        verifying: 'جاري التحقق من الجلسة...',
        lastUpdated: 'آخر تحديث',
        refresh: 'تحديث',
        filter: 'تصفية',
        totalDevices: 'إجمالي الأجهزة',
        registeredUnits: 'الوحدات المسجلة',
        healthy: 'سليم',
        warnings: 'تحذيرات',
        requireReview: 'يتطلب مراجعة',
        critical: 'حرجة',
        actionRequired: 'إجراء مطلوب',
        complianceRate: 'معدل الامتثال',
        complianceDesc: 'نسبة الأجهزة التي تحافظ على نطاقات درجات الحرارة المناسبة عبر المنطقة المختارة',
        monitoringActive: 'المراقبة نشطة',
        readings24h: 'قراءات (24 ساعة)',
        wilayas: 'الولايات المغطاة',
        activeUnits: 'الوحدات النشطة',
        reliability: 'موثوقية النظام',
        assetLocation: 'الموقع الجغرافي للأصول',
        activeMarkers: 'علامات GPS النشطة',
        recentAlerts: 'التنبيهات الأخيرة',
        alertsDesc: 'إشعارات تتطلب الانتباه',
        tempTrend: 'تجميع درجات الحرارة (24 ساعة)',
        trendDesc: 'تطورات درجة الحرارة والرطوبة في كامل النظام',
        monitoredAssets: 'الأصول المراقبة',
        devicesDesc: 'الأجهزة المحدثة مؤخراً',
        viewAll: 'عرض الكل',
        noDevices: 'لا توجد أجهزة مراقبة بعد.',
        language: 'اللغة',
        theme: 'المظهر',
        unauthorized: 'غير مصرح',
        backToLogin: 'العودة لتسجيل الدخول',
        allClear: 'كل شيء سليم!',
        noAlerts: 'لا توجد تنبيهات نشطة حالياً',
        welcomeBack: 'مرحباً بعودتك',
        signInDesc: 'قم بتسجيل الدخول للوصول إلى لوحة التحكم الخاصة بك',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        signIn: 'تسجيل الدخول',
        rememberMe: 'تذكرني',
        forgotPassword: 'نسيت كلمة المرور؟',
        securityNotice: 'محمي بتشفير SSL 256 بت',
        // Alerts
        systemNotifications: 'إشعارات النظام',
        systemNotificationsDesc: 'تنبيهات في الوقت الفعلي تتطلب الانتباه',
        activeAlerts: 'تنبيهات نشطة',
        markAllRead: 'تحديد الكل كمقروء',
        applyFilters: 'تطبيق المرشحات',
        // Facilities
        facilitiesNetwork: 'شبكة المرافق',
        facilitiesDesc: 'إدارة جميع نقاط المستشفيات والمستودعات',
        searchFacilities: 'البحث في المرافق...',
        newFacility: 'مرفق جديد',
        hospital: 'مستشفى',
        warehouse: 'مستودع',
        clinic: 'عيادة',
        hub: 'محور',
        storage: 'تخزين',
        remote: 'بعيد',
        // Devices
        registerNewNode: 'تسجيل عقدة جديدة',
        identity: 'الهوية',
        serialNumber: 'الرقم التسلسلي',
        type: 'النوع',
        location: 'الموقع',
        select: 'تحديد...',
        parameters: 'المعلمات',
        target: 'الهدف',
        min: 'الحد الأدنى',
        max: 'الحد الأقصى',
        cancel: 'إلغاء',
        status: 'الحالة',
        lastReading: 'آخر قراءة',
        battery: 'البطارية',
        actions: 'إجراءات',
        edit: 'تعديل',
        delete: 'حذف',
        viewDetails: 'عرض التفاصيل',
        deviceRegistered: 'تم تسجيل الجهاز بنجاح',
        registrationFailed: 'فشل التسجيل',
        // Common
        active: 'نشط',
        loading: 'جاري التحميل...',
        save: 'حفظ',
        close: 'إغلاق',
        error: 'خطأ',
        success: 'نجاح',
        logs: 'السجلات',
        temp: 'حرارة',
        current: 'الحالي',
        fridge: 'ثلاجة',
        freezer: 'مجمّد',
        device: 'جهاز',
        info: 'معلومات',
        unit: 'وحدة',
        sensors: 'أجهزة الاستشعار',
        sensorState: 'حالة أجهزة الاستشعار',
        online: 'متصل',
        offline: 'غير متصل',
        sendingData: 'يجب استلام البيانات',
    }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>(() => {
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('lang') as Language;
            return saved && ['en', 'fr', 'ar'].includes(saved) ? saved : 'en';
        }
        return 'en';
    });
    const [theme, setTheme] = useState<Theme>(() => {
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('theme') as Theme;
            return saved && ['light', 'dark', 'night'].includes(saved) ? saved : 'dark';
        }
        return 'dark';
    });

    // Apply theme and direction
    useEffect(() => {
        document.documentElement.setAttribute('data-theme', theme);
        document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
        document.documentElement.setAttribute('lang', language);
        localStorage.setItem('lang', language);
        localStorage.setItem('theme', theme);
    }, [language, theme]);

    const t = (key: string) => translations[language][key] || key;

    return (
        <SettingsContext.Provider value={{ language, setLanguage, theme, setTheme, t }}>
            {children}
        </SettingsContext.Provider>
    );
}

export function useSettings() {
    const context = useContext(SettingsContext);
    if (!context) throw new Error('useSettings must be used within SettingsProvider');
    return context;
}
