'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';
type Theme = 'light' | 'dark' | 'night';

interface SettingsContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    theme: Theme;
    setTheme: (theme: Theme) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        dashboard: 'Dashboard',
        dashboardOverview: 'System Overview',
        dashboardWelcome: 'Monitoring cold chain efficiency and network compliance.',
        live: 'Live',
        total: 'Total',
        actionReq: 'Action Required',
        dataVerified: 'Verified',
        complianceText: 'System stability is within nominal parameters. {count} events detected.',
        viewPatternAnalysis: 'Pattern Analysis',
        recentActivity: 'Recent Activity',
        temperatureWarning: 'Thermal Deviation',
        viewAllHistory: 'View History',
        nationalDashboard: 'Healthy Tag Command',
        monitoringSystem: 'Cold Chain Compliance',
        devices: 'Devices',
        manageDevices: 'Hardware registry and telemetry',
        searchDevices: 'Search...',
        addDevice: 'Add Device',
        map: 'Map',
        alerts: 'Alerts',
        manageAlerts: 'Review thermal excursions',
        severity: 'Severity',
        reports: 'Reports',
        generateReports: 'Compliance analytics',
        users: 'Users',
        manageUsers: 'Admin hierarchy and permissions',
        settings: 'Settings',
        preferences: 'Platform behavior and UI',
        profile: 'Profile',
        appearance: 'Appearance',
        logout: 'Sign Out',
        lastUpdated: 'Last update',
        refresh: 'Sync',
        healthy: 'Operational',
        warnings: 'Warning',
        critical: 'Critical',
        complianceRate: 'Compliance Rate',
        activeUnits: 'Active Units',
        activeMarkers: 'GPS Active',
        email: 'Email',
        password: 'Password',
        signIn: 'Sign In',
        signInDesc: 'Authenticate to access the platform',
        admin: 'Admin',
        roleScope: 'Role & Scope',
        contact: 'Contact',
        status: 'Status',
        addRegionalAdmin: 'Add Regional Admin',
        registerNewAdmin: 'Register Administrator',
        regionalAdmin: 'Regional Admin',
        localAdmin: 'Local Admin',
        systemAdmin: 'System Admin',
        assignedRegion: 'Assigned Region',
        firstName: 'First Name',
        lastName: 'Last Name',
        processing: 'Processing...',
        registerAdmin: 'Register Admin',
        light: 'Light',
        dark: 'Dark',
        night: 'Night',
        security: 'Security',
        accountProtection: 'Account Protection',
        resetPassword: 'Reset Password',
        platformConfig: 'Settings',
        nationalScope: 'National Scope',
        allSystemsHealthy: 'All systems healthy',
        noRecentAlerts: 'No recent alerts',
        role: 'Role',
        select: 'Select...',
        cancel: 'Cancel',
        securityNotice: 'Protected by Healthy Tag Identity Service',
        fleetIntelligence: 'Fleet Intelligence',
        activeHardwareCount: 'active hardware nodes',
        manage: 'Manage',
        unassigned: 'Unassigned',
        fixManual: 'Fix Manual',
        forceAlert: 'Force Alert',
        telemetryLogs: 'Telemetry Logs',
        noLogsFound: 'No logs found for this period',
        registerNewNode: 'Register New Node',
        serialNumber: 'Serial Number',
        identity: 'Identity',
        type: 'Type',
        fridge: 'Fridge',
        freezer: 'Freezer',
        parameters: 'Parameters',
        target: 'Target',
        min: 'Min',
        max: 'Max',
        logs: 'Logs',
        edit: 'Edit',
        delete: 'Delete',
        device: 'Device',
        location: 'Location',
        temp: 'Temp',
        forgotPassword: 'Forgot Password?',
        invalidCredentials: 'Invalid Credentials',
        systemError: 'System Communication Error',
        systemNotifications: 'System Notifications',
        activeAlerts: 'Active Alerts',
        acknowledge: 'Acknowledge',
        resolve: 'Resolve',
        noActiveAlerts: 'No active alerts',
        monitoringNodesNormal: 'All monitoring nodes are operating within normal parameters.',
        filter: 'Filter',
        applyFilters: 'Apply Filters',
        info: 'Information',
        tempCompliance: 'Temperature Compliance',
        alarmHistory: 'Alarm History',
        assetInventory: 'Asset Inventory',
        exportPDF: 'Export PDF',
        assetInventoryStatus: 'Asset Inventory Status',
        never: 'Never',
        deviceId: 'Device ID',
        facility: 'Facility',
        wilaya: 'Wilaya'
    },
    fr: {
        dashboard: 'Tableau de bord',
        dashboardOverview: 'Vue d\'ensemble',
        dashboardWelcome: 'Surveillance de la chaîne du froid et conformité.',
        live: 'En direct',
        total: 'Total',
        actionReq: 'Action Requise',
        dataVerified: 'Vérifié',
        complianceText: 'La stabilité du système est nominale. {count} événements détectés.',
        viewPatternAnalysis: 'Analyse des tendances',
        recentActivity: 'Activité récente',
        temperatureWarning: 'Déviation thermique',
        viewAllHistory: 'Voir l\'historique',
        nationalDashboard: 'Commande Healthy Tag',
        monitoringSystem: 'Conformité chaîne du froid',
        devices: 'Appareils',
        manageDevices: 'Registre matériel et télémétrie',
        searchDevices: 'Rechercher...',
        addDevice: 'Ajouter Appareil',
        map: 'Carte',
        alerts: 'Alertes',
        manageAlerts: 'Revoir les excursions thermiques',
        severity: 'Gravité',
        reports: 'Rapports',
        generateReports: 'Analyses de conformité',
        users: 'Utilisateurs',
        manageUsers: 'Hiérarchie et permissions',
        settings: 'Paramètres',
        preferences: 'Comportement et interface',
        profile: 'Profil',
        appearance: 'Apparence',
        logout: 'Déconnexion',
        lastUpdated: 'Dernière mise à jour',
        refresh: 'Sync',
        healthy: 'Opérationnel',
        warnings: 'Avertissement',
        critical: 'Critique',
        complianceRate: 'Taux de Conformité',
        activeUnits: 'Unités Actives',
        activeMarkers: 'GPS Active',
        email: 'Email',
        password: 'Mot de passe',
        signIn: 'Connexion',
        signInDesc: 'Authentifiez-vous pour accéder',
        admin: 'Admin',
        roleScope: 'Rôle & Portée',
        contact: 'Contact',
        status: 'Statut',
        addRegionalAdmin: 'Ajouter Admin Régional',
        registerNewAdmin: 'Enregistrer Administrateur',
        regionalAdmin: 'Admin Régional',
        localAdmin: 'Admin Local',
        systemAdmin: 'Admin Système',
        assignedRegion: 'Région Assignée',
        firstName: 'Prénom',
        lastName: 'Nom',
        processing: 'Traitement...',
        registerAdmin: 'Enregistrer Admin',
        light: 'Clair',
        dark: 'Sombre',
        night: 'Nuit',
        security: 'Sécurité',
        accountProtection: 'Protection du Compte',
        resetPassword: 'Changer Mot de Passe',
        platformConfig: 'Paramètres',
        nationalScope: 'Portée Nationale',
        allSystemsHealthy: 'Tous les systèmes sont opérationnels',
        noRecentAlerts: 'Aucune alerte récente',
        role: 'Rôle',
        select: 'Sélectionner...',
        cancel: 'Annuler',
        securityNotice: 'Protégé par le service d\'identité Healthy Tag',
        fleetIntelligence: 'Intelligence de Flotte',
        activeHardwareCount: 'nœuds matériels actifs',
        manage: 'Gérer',
        unassigned: 'Non assigné',
        fixManual: 'Corriger manuellement',
        forceAlert: 'Forcer l\'alerte',
        telemetryLogs: 'Journaux de télémétrie',
        noLogsFound: 'Aucun journal trouvé pour cette période',
        registerNewNode: 'Enregistrer un nouveau nœud',
        serialNumber: 'Numéro de série',
        identity: 'Identité',
        type: 'Type',
        fridge: 'Réfrigérateur',
        freezer: 'Congélateur',
        parameters: 'Paramètres',
        target: 'Cible',
        min: 'Min',
        max: 'Max',
        logs: 'Logs',
        edit: 'Modifier',
        delete: 'Supprimer',
        device: 'Appareil',
        location: 'Emplacement',
        temp: 'Temp',
        forgotPassword: 'Mot de passe oublié ?',
        invalidCredentials: 'Identifiants invalides',
        systemError: 'Erreur de communication système',
        systemNotifications: 'Notifications Système',
        activeAlerts: 'Alertes Actives',
        acknowledge: 'Acquitter',
        resolve: 'Résoudre',
        noActiveAlerts: 'Aucune alerte active',
        monitoringNodesNormal: 'Tous les nœuds de surveillance fonctionnent normalement.',
        filter: 'Filtrer',
        applyFilters: 'Appliquer Filtres',
        info: 'Information',
        tempCompliance: 'Conformité Thermique',
        alarmHistory: 'Historique des Alarmes',
        assetInventory: 'Inventaire des Actifs',
        exportPDF: 'Exporter PDF',
        assetInventoryStatus: 'Statut de l\'Inventaire des Actifs',
        never: 'Jamais',
        deviceId: 'ID de l\'Appareil',
        facility: 'Installation',
        wilaya: 'Wilaya'
    },
    ar: {
        dashboard: 'الرئيسية',
        dashboardOverview: 'نظرة عامة على النظام',
        dashboardWelcome: 'مراقبة كفاءة سلسلة التبريد والامتثال عبر المؤسسة.',
        live: 'مباشر',
        total: 'الإجمالي',
        actionReq: 'إجراء مطلوب',
        dataVerified: 'بيانات مؤمنة',
        complianceText: 'استقرار الأسطول ضمن المعايير الاسمية. تم رصد {count} تنبيه.',
        viewPatternAnalysis: 'تحليل الأنماط الذكي',
        recentActivity: 'النشاطات الأخيرة',
        temperatureWarning: 'انحراف حراري',
        viewAllHistory: 'عرض السجلات',
        nationalDashboard: 'مركز تحكم Healthy Tag',
        monitoringSystem: 'منصة نظام التبريد',
        devices: 'الأجهزة',
        manageDevices: 'إدارة أجهزة إنترنت الأشياء',
        searchDevices: 'بحث...',
        addDevice: 'إضافة جهاز',
        map: 'الخريطة',
        alerts: 'تنبيهات النظام',
        manageAlerts: 'مراجعة التنبيهات الحرجة',
        severity: 'الخطورة',
        reports: 'التقارير',
        generateReports: 'تحليلات الامتثال',
        users: 'المستخدمين',
        manageUsers: 'إدارة المشرفين والصلاحيات',
        settings: 'الإعدادات',
        preferences: 'تفضيلات المنصة والمظهر',
        profile: 'الملف الشخصي',
        appearance: 'المظهر',
        logout: 'تسجيل الخروج',
        lastUpdated: 'آخر تحديث',
        refresh: 'تحديث البيانات',
        healthy: 'يعمل',
        warnings: 'تحذير',
        critical: 'حرج للغاية',
        complianceRate: 'مؤشر الامتثال',
        activeUnits: 'الوحدات النشطة',
        activeMarkers: 'مواقع GPS',
        email: 'البريد المؤسسي',
        password: 'كلمة المرور',
        signIn: 'دخول',
        signInDesc: 'الرجاء تسجيل الدخول للوصول',
        admin: 'مدير',
        roleScope: 'الصلاحية والنطاق',
        contact: 'قناة الاتصال',
        status: 'الحالة',
        addRegionalAdmin: 'إضافة مسؤول إقليمي',
        registerNewAdmin: 'تسجيل حساب إداري',
        regionalAdmin: 'مشرف إقليمي',
        localAdmin: 'مشرف محلي',
        systemAdmin: 'مدير النظام',
        assignedRegion: 'النطاق الجغرافي',
        firstName: 'الاسم',
        lastName: 'اللقب',
        processing: 'جاري المعالجة...',
        registerAdmin: 'تأكيد التسجيل',
        light: 'نهاري',
        dark: 'ليلي',
        night: 'شديد السواد',
        security: 'الأمان',
        accountProtection: 'حماية الحساب',
        resetPassword: 'تغيير كلمة المرور',
        platformConfig: 'إعدادات المنصة',
        nationalScope: 'النطاق الوطني',
        allSystemsHealthy: 'جميع الأنظمة تعمل بكفاءة',
        noRecentAlerts: 'لا توجد تنبيهات حديثة',
        role: 'الرتبة الإدارية',
        select: 'اختر المرفق...',
        cancel: 'إلغاء',
        securityNotice: 'محمي بواسطة نظام Healthy Tag لإدارة الهوية',
        fleetIntelligence: 'ذكاء الأسطول المركزي',
        activeHardwareCount: 'أجهزة نشطة في النظام',
        manage: 'إدارة',
        unassigned: 'غير معين',
        fixManual: 'معالجة يدوية',
        forceAlert: 'تنبيه قسري',
        telemetryLogs: 'سجلات القياس للوحدة',
        noLogsFound: 'لا توجد سجلات حالياً لهذه الفترة',
        registerNewNode: 'تسجيل جهاز جديد',
        serialNumber: 'الرقم التسلسلي S/N',
        identity: 'هوية الجهاز',
        type: 'نوع الوحدة',
        fridge: 'ثلاجة تبريد',
        freezer: 'مجمد حراري',
        parameters: 'المعايير التقنية',
        target: 'الحرارة المستهدفة',
        min: 'الأدنى',
        max: 'الأقصى',
        logs: 'سجل العمليات',
        edit: 'تعديل',
        delete: 'حذف الوحدة',
        device: 'الجهاز الرقمي',
        location: 'الموقع الجغرافي',
        temp: 'درجة الحرارة',
        forgotPassword: 'نسيت كلمة المرور؟',
        invalidCredentials: 'بيانات الدخول غير صحيحة',
        systemError: 'خطأ في الاتصال بالخادم',
        systemNotifications: 'تنبيهات النظام',
        activeAlerts: 'التنبيهات النشطة',
        acknowledge: 'اعتراف',
        resolve: 'حل المشكل',
        noActiveAlerts: 'لا توجد تنبيهات نشطة',
        monitoringNodesNormal: 'جميع عقد المراقبة تعمل ضمن المعايير الطبيعية.',
        filter: 'تصفية',
        applyFilters: 'تطبيق التصفية',
        info: 'معلومات',
        tempCompliance: 'الامتثال الحراري',
        alarmHistory: 'سجل التنبيهات',
        assetInventory: 'جرد الأصول',
        exportPDF: 'تصدير PDF',
        assetInventoryStatus: 'حالة جرد الأصول',
        never: 'مطلقاً',
        deviceId: 'معرف الجهاز',
        facility: 'المرفق',
        wilaya: 'الولاية'
    }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');
    const [theme, setTheme] = useState<Theme>('dark');
    const [mounted, setMounted] = useState(false);

    // Initialize from localStorage on mount
    useEffect(() => {
        const savedLang = localStorage.getItem('lang') as Language;
        if (savedLang && ['en', 'fr', 'ar'].includes(savedLang)) {
            setLanguage(savedLang);
        }
        const savedTheme = localStorage.getItem('theme') as Theme;
        if (savedTheme && ['light', 'dark', 'night'].includes(savedTheme)) {
            setTheme(savedTheme);
        }
        setMounted(true);
    }, []);

    // Apply theme and direction
    useEffect(() => {
        if (!mounted) return;
        document.documentElement.setAttribute('data-theme', theme);
        document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
        document.documentElement.setAttribute('lang', language);
        localStorage.setItem('lang', language);
        localStorage.setItem('theme', theme);
    }, [language, theme, mounted]);

    const t = (key: string) => translations[language][key] || key;

    return (
        <SettingsContext.Provider value={{ language, setLanguage, theme, setTheme, t }}>
            {children}
        </SettingsContext.Provider>
    );
}

export function useSettings() {
    const context = useContext(SettingsContext);
    if (!context) throw new Error('useSettings must be used within SettingsProvider');
    return context;
}
